FROM ros:noetic-ros-core

ARG DEBIAN_FRONTEND=noninteractive

# Install build dependencies
RUN apt-get update && \
    apt-get install -y \
      build-essential \
      python3-catkin-tools && \
    apt-get clean

# Install util_caching
COPY . /tmp/util_caching
RUN mkdir /tmp/util_caching/build && \
    cd /tmp/util_caching/build && \
    cmake .. && \
    cmake --build . && \
    cmake --install . && \
    rm -rf /tmp/util_caching


RUN useradd --create-home --uid 1000 blinky
USER blinky

WORKDIR /home/blinky/

# Build the demo in a catkin workspace
COPY --chown=blinky:blinky demo /home/blinky/catkin_ws/src/demo
RUN cd /home/blinky/catkin_ws/ && \
    . /opt/ros/noetic/setup.sh && \
    catkin init && \
    catkin build

# Run a ROS core in the background
CMD . /opt/ros/noetic/setup.sh && \
    roscore >/dev/null & bash
