name: Create Release
on:
  push:
    tags:
      - "v*"

jobs:
  build-and-release:
    permissions:
      contents: write

    runs-on: ubuntu-latest
    steps:
      - name: Build release packages
        uses: docker/build-push-action@v6
        with:
          outputs: |
            type=local,dest=/tmp/artifacts
          push: false
          target: release

      - name: Verify release directory contents
        run: ls /artifacts && ls -R /artifacts/release

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "/tmp/artifacts/release/*"

